### PR TITLE
12.0 mcfix migrations

### PR DESCRIPTION
**Pull request by jarroyomorales**
Migration of:
* mcfix_account_bank_statement_import
* mcfix_account_check_printing

### CODE REVIEW

**Review by etobella — CHANGES_REQUESTED** [review]
Do not migrate mcfix_base_model_create_hook please

**Comment by jarroyomorales** [comment]
@etobella Removed that module from migration and Travis green

**Comment by JordiBForgeFlow** [comment]
@jarroyomorales but the module mcfix_base_model_create_hook is in the commit as if it is being removed. Perhaps it just should not be included?

Perhaps you should apply the migration again, this time only selecting the two modules that you want to migrate.

**Comment by jarroyomorales** [comment]
@jbeficent Yes, I think that will be easier, at the end I'm only changing the version number...

**Pull request closed without merging**
