### PR TITLE
[15.0][MIG] multicompany_property_product

### PR DESCRIPTION
**Pull request by JuanyDForgeflow**
Depends on https://github.com/ForgeFlow/multicompany-fixes/pull/144

This module is part of a set of modules that allow to set property fields on
a given model for multiple companies simultaneously. Specifically this module:

* Adds a new page 'Multi company' in the product and product category that
  allows the user to maintain, for all companies, the company-specific fields
  of one product.

### CODE REVIEW

**Comment by JuanyDForgeflow** [comment]
@MiquelRForgeFlow any idea how to fix pre-commit?

**Comment by MiquelRForgeFlow** [comment]
Problem solved. Please rebase.

**Review by MiquelRForgeFlow — APPROVED** [review]
LGTM

**Pull request merged**
